### GET request to example server
POST {{host}}/lobby
Content-Type: application/json

{
  "name": "Player 1",
  "team": "The A Team",
  "password": "password"
}

###
POST {{host}}/lobby
Content-Type: application/json

{
  "name": "Player 2",
  "team": "The A Team",
  "password": "password2"
}

###
GET {{host}}/state

###

POST {{host}}/control
Content-Type: application/json

{
  "password": "password",
  "thrust": 1,
  "rotation": 0
}
###

POST {{host}}/control
Content-Type: application/json

{
  "password": "password2",
  "thrust": 0,
  "rotation": 10
}
